version: "3"
services:
  simple-instagram-bot:
    build: .
    restart: always
    volumes:
      - ./app:/app
    logging:
      driver: "json-file"
      options:
          max-size: "2m"
          max-file: "10"
    environment:
      - API_TOKEN=<5002292255:AAEoPoYSRdMiWK6F4ch2x_jO4UQc7BKkKPA>
